### PR TITLE
Missing exception warnings

### PR DESCRIPTION
**Pull request by nanjekyejoannah**
Dont review until [this](https://github.com/softdevteam/pygrate2/pull/12) is merged.

### CODE REVIEW

**Comment by ltratt** [comment]
This looks fine to me. Please squash.

**Comment by nanjekyejoannah** [comment]
I still need to move some rules to `ceval` from the AST. Please bear with me as I try to understand a better place.

**Comment by nanjekyejoannah** [comment]
This will wait for some time, until I move some helper code related to `ceval`.

**Comment by ltratt** [comment]
@nanjekyejoannah Is this one ready for merging now?

**Comment by nanjekyejoannah** [comment]
I have one more PR on my list of 68 things before we come back here. I can certainly get like 4 exception warnings merged as part of this PR and leave what what is making this PR wait, but I prefer to wait to handle all exceptions with the helpers in ceval.

I will do that next after these open PRs are merged, just the dict PR, then this is next thing after.

**Comment by ltratt** [comment]
If you're happy to wait, I'm fine with that!

**Comment by ltratt** [comment]
Where are we with this one?

**Comment by nanjekyejoannah** [comment]
I think lets merge this, I am delayng it because of scope. I will commit the scope PR as a separate topic with other things that involve scope e.g exec, etc. I will handle scope as one topic for all things on my list, Some exception warnings, I already separated before, like the 3 component PR.

**Comment by ltratt** [comment]
Please squash.

**Comment by nanjekyejoannah** [comment]
Squashed.

**Pull request closed without merging**
