### PR TITLE
Initial CI support.

### PR DESCRIPTION
**Pull request by vext01**
This is preliminary CI support for CPython.

A test is failing:
```
test test_signal failed -- Traceback (most recent call last):
  File "/ci/Lib/test/test_signal.py", line 184, in test_main
    self.fail(tb)
AssertionError: Traceback (most recent call last):
  File "/ci/Lib/test/test_signal.py", line 167, in test_main
    self.run_test()
  File "/ci/Lib/test/test_signal.py", line 94, in run_test
    child = ignoring_eintr(subprocess.Popen, ['kill', '-HUP', str(pid)])
  File "/ci/Lib/test/test_signal.py", line 32, in ignoring_eintr
    return __func(*args, **kwargs)
  File "/ci/Lib/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/ci/Lib/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Does anyone know anything about it? Could have cloned at a bad time?

### CODE REVIEW

**Comment by vext01** [comment]
Full build log: http://ci.soft-dev.org/#/builders/1/builds/1604/steps/2/logs/stdio

**Comment by ltratt** [comment]
@nanjekyejoannah Any ideas?

**Comment by ltratt** [comment]
I vaguely remember that @drpdr has seen this error in the past?

**Comment by vext01** [comment]
It only seems to occur when inside buildbot and/or docker.

**Comment by ltratt** [comment]
To be honest, I'd be fine with skipping this one test, but it'll be interesting to see if a) @drpdr did see this b) if there was a fix.

[Perhaps Docker + signals don't work in the way we expect?]

**Comment by drpdr** [comment]
> I vaguely remember that @drpdr has seen this error in the past?

I tried to find `test_signal` in my old notes but I couldn't find anything useful. I had issues with `limits` in the past but that was splitter-related. What happens if you run it in isolation, @vext01 : `./python3 -m test --match test_signal`?

**Comment by vext01** [comment]
Do you mean running that one test in isolation?

That seems to work outside of docker/buildbot:
```
vext01@bencher13:~/research/cpython-migration$ ./python -m test test_signal
Run tests sequentially
0:00:00 load avg: 3.08 [1/1] test_signal

== Tests result: SUCCESS ==
```

I've not tried inside, but really we need all tests to pass if possible.

**Comment by drpdr** [comment]
> Do you mean running that one test in isolation?
> 
> That seems to work outside of docker/buildbot:
> 
> ```
> vext01@bencher13:~/research/cpython-migration$ ./python -m test test_signal
> Run tests sequentially
> 0:00:00 load avg: 3.08 [1/1] test_signal
> 
> == Tests result: SUCCESS ==
> ```
> 
> I've not tried inside, but really we need all tests to pass if possible.

Yes. OK. Can you try it inside the container as single test to isolate that `No such file or directory` further?

**Comment by ltratt** [comment]
I'm pretty sure the "no such file or directory" file is what @drpdr ran into previously. My memory is that we didn't solve it.

Anyway, the "obvious" culprit is signals under Docker. For example, are we running things as PID 1? https://petermalmgren.com/signal-handling-docker/ suggests that `dumb-init` might be worth us doing?

**Comment by drpdr** [comment]
> I'm pretty sure the "no such file or directory" file is what @drpdr ran into previously. My memory is that we didn't solve it.
> 
> Anyway, the "obvious" culprit is signals under Docker. For example, are we running things as PID 1? https://petermalmgren.com/signal-handling-docker/ suggests that `dumb-init` might be worth us doing?

We use `dumb-init` in the CapableVMs infrastructure but for other reasons, i.e. zombies. It may be worth trying.

**Comment by drpdr** [comment]
> > I'm pretty sure the "no such file or directory" file is what @drpdr ran into previously. My memory is that we didn't solve it.
> > Anyway, the "obvious" culprit is signals under Docker. For example, are we running things as PID 1? https://petermalmgren.com/signal-handling-docker/ suggests that `dumb-init` might be worth us doing?
> 
> We use `dumb-init` in the CapableVMs infrastructure but for other reasons, i.e. zombies. It may be worth trying.

Oh but that could be related because test runs produce a great quantity of (dead) granchild processes. So in isolation `test_signal` may not fail, but it could fail after many other tests. So, `dumb-init` could solve it.

**Comment by vext01** [comment]
I don't see how dumb-init could help.

If i read it right, `.buildbot.sh` would be PID #1, then anything it calls (i.e. `python -m test`) is then forked, and cannot have PID #1.

**Comment by ltratt** [comment]
PID 1 has to do certain things that a shell probably doesn't do. Why not try it and see? It's probably a good idea for all our containers IIUC.

**Comment by vext01** [comment]
OK. Bear with me. I'm still reproducing locally.

**Comment by vext01** [comment]
Funny. The file it can't find is actually `/bin/ps` :laughing: 

I'm going to add `ps` to the default image.

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
Looks promising: http://ci.soft-dev.org/#/builders/1/builds/1606

If the build succeeds, then I think that's bors configured correctly.

One thing you folks need to discuss it what optional modules you want to test. The build system skips tests for optional modules which were not compiled-in (due to missing dependencies). If you want to test those too, you will need to build a custom docker config with all the necessary deps.

You would make a file like this in the top-level of the repo, then customise the packages to your requirements:
https://github.com/softdevteam/softdevbib/blob/master/.buildbot_dockerfile_debian

Don't forget to include the `procps` package, as we know the Python test suite requires it.

**Comment by ltratt** [comment]
Thanks @vext01!

bors r+

**Comment by vext01** [comment]
> The build system skips tests for optional modules which were not compiled-in (due to missing dependencies)

Here is what is currently being skipped:

```
Python build finished, but the necessary bits to build these modules were not found:
_bsddb             _curses            _curses_panel   
_sqlite3           _ssl               _tkinter        
bsddb185           bz2                dbm             
dl                 gdbm               imageop         
readline           sunaudiodev        zlib            
To find the necessary bits, look in setup.py in detect_modules() for the module's name.
```

**Pull request merged**
